### ISSUE TITLE
different eve output between compilers 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/ktools#119]
**git installed oasislmf**
```
$ eve -v 
eve : version: 3.2.5
eve : compiler: gcc 8.3.0 
```

(Piwind 1.7.0)
```
$ eve 1 1 | evetocsv | head -25
event_id
732
1139
72
1332
811
38
935
1277
50
861
1015
498
1231
126
230
1229
1157
835
1221
947
215
487
1093
1130
```

**Binary packaged eve** (oasislmf==1.7.0)
```
$ eve -v
eve : version: 3.2.5 - git update: Fri Apr 17 13:22:09 2020 +0100t
eve : compiler: 9.0.0 (https://github.com/llvm/llvm-project.git f3dc4a40792fbf1b21dcd804d2bcf0b865ab75ac)
```
(Piwind 1.7.0)
```
$ eve 1 1 | evetocsv | head -25
event_id
1272
668
946
312
934
250
749
270
899
978
1000
1240
655
1311
1379
402
39
1
150
437
886
615
1365
642
```

**Comment by sambles** [comment]
> **Hassan Chagani** 
I think it might be the difference between how std::shuffle is implemented in gcc v.6.3.0 (coreoasis/model_worker:1.6.0) and gcc v.8.3.0 (coreoasis/model_worker:1.7.0). Looking at the source code in the algorithm library, there are some differences.

> **pinkerton**
It might be worth sorting the final elt output. By default, you would probably expect it ordered by event_id.

**Comment by mpinkerton-oasis** [comment]
Imposing order on the ELT at the end if the agreed approach.

**Comment by hchagani-oasislmf** [comment]
This is to do with the way `std::shuffle` has been implemented. There remains the question of whether this issue is important. As stated above, imposing order on output of `eltcalc` is the agreed approach. However, this is not a trivial task (a separate issue exists for this; see https://github.com/OasisLMF/ktools/issues/36).

There are two options:

1. Create and call our own `shuffle()` function. In this way, any changes to `std::shuffle` in the future will not affect us. We can also tailor this function to our particular needs rather than rely on a general one provided in the algorithm library.
2. Employ a deterministic approach by assigning events to processes in the same way a deck of cards is dealt. Not only would the execution time be faster; the sorting of the `eltcalc` output would be easier as the location of event IDs would be known.

The mean times for the aforementioned options over 100 tests to distribute 1,000,000 event IDs to a single process ID are as follows:

```
$ ./a.out > /dev/null
Fisher-Yates Shuffle:
Mean time taken = 102.364705 ms

Deterministic:
Mean time taken = 16.466846 ms
```

These compare with a mean time of 130.3 ms (over 10 tests) from `eve 2 8 > /dev/null`.

For reference, the implementation of the Fisher-Yates shuffle is as follows:

```
  // Shuffle events
  auto eventsSize = events.size();
  unsigned seed = 1234;
  std::default_random_engine e(seed);
  int counter = 1;
  // For this test, let's assume we are process 2 out of 8
  const int processID = 2;
  const int totalProcesses = 8;
  for (std::vector<int>::iterator i = events.begin(); i != events.end(); i++)
  {
    // Implement Fisher-Yates shuffle
    std::uniform_int_distribution<> d(0, --eventsSize);
    std::iter_swap(i, i + d(e));

    // If we work under the assumption that there are 8 processes, and that we
    // only consider swapping each element once as we go through the vector
    // sequentially, we can output event IDs as we proceed.
    if ((counter - processID) % totalProcesses == 0) {
      fwrite(&(*i), sizeof(*i), 1, stdout);
    }
    counter++;
  }
```

The implementation of the deterministic approach is as follows:

```
  // For this test, let's assume we are process 2 out of 8
  const int processID = 2;
  const int totalProcesses = 8;
  // As event IDs are being read from file, assign them to processes in the same
  // fashion as dealing a deck of cards. We are only interested in a particular
  // process ID.
  int counter = 1;
  int eventID;
  while (fread(&eventID, sizeof(eventID), 1, fin) == 1) {
    if ((counter - processID) % totalProcesses == 0) {
      fwrite(&eventID, sizeof(eventID), 1, stdout);
    }
    counter++;
  }
```
