### ISSUE TITLE
vulnerability.idx file

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#155]
Can we add in a the option for a vulnerability.idx offset index file to accompany vulnerability.bin, in the same way that we do for footprint? This should be an optional file which will be used if it is present but should improve performance for very large vulnerability files.

**Comment by hchagani-oasislmf** [comment]
@benhayes21 has suggested adding a compression option. It would be preferable to do this now rather than add it on later.

As there are cases when we can exceed a machine's memory when setting the size of an output buffer in order to inflate zipped footprint data (see https://github.com/OasisLMF/ktools/issues/165), the `vulnerability.idx` file should always contain the size of the uncompressed data. This is because there is no suitable header in `vulnerability.bin` to indicate whether the original size of the string is included in the index file.

If there is no compression, the value in the index file should be present anyway but would be ignored by `getmodel`.
