### ISSUE TITLE
eltcalc partial failures

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#172]
if an eltcalc process fails in flow it will leave an incomplete output csv file but will not pass an error to stderror. This means that we can end up with incomplete ELT output files with missing events.

**Comment by hchagani-oasislmf** [comment]
An example of this is shown below:

```
1,1,19589,18325.179688,0,593187392.000000
1,2,19589,18651.916016,1,1,34908,86976.335938,0,5297785344.000000
1,2,34908,86426.953125,16902.863281,5297785344.000000
```

It appears as though the output is being interrupted as there is no new line character (`eltcalc.cpp` L113):

```
                                if (samplesize) printf("%d,2,%d,%f,%f,%f\n", sh.summary_id, sh.event_id, sample_mean, sd, sh.expval);
```

According to the `write(2)` manual page:

>The number of bytes written may be less than  count  if,  for  example, there  is  insufficient space on the underlying physical medium, or the RLIMIT_FSIZE resource limit is encountered (see setrlimit(2)),  or  the call was interrupted by a signal handler after having written less than count bytes.  (See also pipe(7).)

This may be what is happening in this case. `eltcalc::doetloutput()` returns, so the issue is not picked up in the log files:

```
$ grep starting eltcalc_* | wc -l
128
$ grep finishing eltcalc_* | wc -l
128
```

As this is a partial output, `printf` will not return a negative number as an error code because it believes it has succeeded. It will instead return the number of characters written. Perhaps, by cross-checking the number of characters written, multiple attempts can be made to write a line and/or an error message can be issued.
