### ISSUE TITLE
OASIS_FLOAT in kat

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#215]
## Issue Description
I believe I have discovered a bug in the ‘kat’ program within KTOOLS while running our model through the oasismdk.

When the precision of the OASIS_FLOAT variable is increased to an 8 byte double, the sscanf commands on lines 85 and 123 are hard coded to read in a 4 byte float, leading to incorrect loss output. The fix is simple and only requires an option to change the sscanf precisions from a 4 byte %f to an 8 byte %lf on lines 85 and 123.

## Steps to Reproduce (Bugs only)

1. generate losses bigger than 4 byte float

**Comment by hchagani-oasislmf** [comment]
Thank you. This is a bug, however it is not restricted to `kat`. It actually extends throughout the package as everywhere where a variable of type `OASIS_FLOAT` is written or read, it is done using the `%f` format specifier.

A better way to set the precision of `OASIS_FLOAT` would be to do something similar to `AREAPERIL_ID` in `include/oasis.h`. For example:

```
// #define OASIS_FLOAT_TYPE_DOUBLE
#ifdef OASIS_FLOAT_TYPE_DOUBLE
typedef double OASIS_FLOAT
#else
typedef float OASIS_FLOAT
#endif
```
One could then uncomment `#define OASIS_FLOAT_TYPE_DOUBLE` in order to set the precision of `OASIS_FLOAT` to that of a `double`. The rest of the package can then determine whether the macro `OASIS_FLOAT_TYPE_DOUBLE` has been defined, and alter the input/output format specifiers in response.

Unfortunately the fix isn't so simple, but it is good you caught it!
