### ISSUE TITLE
Damage bin interval type

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/ktools#38]
As far as I know, this column is no longer used. It causes confusion to new developers. Can we deprecate and remove from documentation?

**Comment by hchagani-oasislmf** [comment]
So that we do not break things, we will need to support the damage bin interval type column. Going forward:

- [ ] `damagebintocsv` should detect and support both 4-column and 5-column format.
- [ ] `damagebintobin` should convert 5-column format to 4-column format unless argument given.
- [ ] `validatedamagebin` should issue a deprecation warning for 5-column format.
- [ ] `cdftocsv` should detect and support both 4-column and 5-column format.
- [ ] `getmodel` should detect and support both 4-column and 5-column format.
- [ ] `gulcalc` should detect and support both 4-column and 5-column format.

This will have a knock-on effect on generating a test `damage_bin_dict.bin` file in the MDK. As generating test files has not been fully implemented into the MDK yet, this can be altered at a later date. The aforementioned changes will have no other effect on the MDK.
