### ISSUE TITLE
eve and evetobin: How to make sure size of event_id is always 4?

### ISSUE THREAD

**Issue by cdlhub** [OasisLMF/ktools#8]
`evetobin.cpp`: `doit()` uses `typeof(int)` to print event id.
`eve.cpp`: `emitevents()` uses hard coded `4` for event id offset.

Wouldn't it be safer to use `sizeof(int32_t)` in both source files?

**Comment by bmatharu** [comment]
Hi

Thank you for you feedback its much appreciated.

I have created an OASIS_INT and OASIS_FLOAT typedefs in so that its easier for people to change the data types to whatever they prefer - This is something we meant to do but now we've started it

I've also removed the hard coding of 4 in eve.

Thanks for your input.
