### ISSUE TITLE
first event_id is dropped using summarycalc -i 

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#86]
debug.tar.gz containing example provided

**Comment by bmatharu** [comment]
This is not a bug - not sure how the gul data stream was generated but the records are in the wrong order - in the gul_type2.bin
Currently event 1 looks like this
event_id,item_id,sidx,loss
1,15,-1,150.00
1,15,-2,0.00
1,15,-3,500.00
1,15,1,150.00
but it should look like this
event_id,item_id,sidx,loss
1,15,-3,500.00
1,15,-2,0.00
1,15,-1,150.00
1,15,1,150.00
The -3 sidx is the exposure value and should be the first element in the gul stream otherwise the process gets interpreted as zero exposure

**Comment by bmatharu** [comment]
Strictly speaking no data should be outputted in this case. This has now been fixed.

**Comment by DanielFEvans** [comment]
Is that ordering requirement documented anywhere? Looking at https://github.com/OasisLMF/ktools/blob/develop/docs/md/Specification.md#loss, I can only see that "sidx -3 to -1 must come at the beginning of the data packet", which doesn't explicitly state that the order of those sidx values is important.

Is the ordering reversed to the old items loss stream? It's also not explicitly stated, but the documentation always shows -1 before -2. If so, that's likely where the issue came from - we'll have kept the ordering the same after converting our code to the new output format.

**Comment by bmatharu** [comment]
Hi Daniel
You are right the documentation was not clear - I have fixed this now. I hope it's clearer.
 https://github.com/OasisLMF/ktools/blob/develop/docs/md/Specification.md#loss

**Comment by DanielFEvans** [comment]
Thanks!
